#!/bin/sh
# rebuild.sh - rebuild everything from scratch

./clean.sh

# Re-fetch gtest.  I read in:
#   http://stackoverflow.com/questions/8507723/how-to-start-working-with-gtest-and-cmake
# that it is much easier to do use gtest from cmake by having the gtest source
# directory right in the project directory.
tar xzf gtest-1.7.0.tz

cat <<__EOF__ >CMakeLists.txt
################################
# CMakeLists.txt
# THIS FILE IS AUTOMATICALLY GENERATED FROM rebuild.sh
# Make changes in rebuild.sh and re-run it.
################################
cmake_minimum_required(VERSION 2.6)
project(basic_test)

# GTest
ADD_SUBDIRECTORY (gtest-1.7.0)
enable_testing()
include_directories(${gtest_SOURCE_DIR}/include ${gtest_SOURCE_DIR})

# Unit Tests
#
# Add test cpp file
add_executable( runUnitTests learn.cpp )
# Link test executable against gtest & gtest_main
target_link_libraries(runUnitTests gtest gtest_main)
add_test( runUnitTests runUnitTests )
__EOF__

cmake -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-std=c++11 -DGTEST_USE_OWN_TR1_TUPLE=1 -Werror -stdlib=libc++ -U__STRICT_ANSI__ -Igtest-1.7.0/include" .

make
